name: Build and Test Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAX_IMAGE_SIZE: 10000000 # 10 MB
      IMAGE_TAG: bugle:latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build . -t ${{ env.IMAGE_TAG }}

    - name: Run Docker image
      run: docker run --rm ${{ env.IMAGE_TAG }}

    - name: Calculate image size
      id: image-size
      run: |
        size=$(docker images ${{ env.IMAGE_TAG }} --format "{{.Size}}")
        size_in_bytes=$(docker inspect ${{ env.IMAGE_TAG }} --format="{{.Size}}")
        echo "Image size: $size"
        echo "Image size in bytes: $size_in_bytes"
        echo "size=$size_in_bytes" >> $GITHUB_OUTPUT

    - name: Check image size
      run: |
        if [ ${{ steps.image-size.outputs.size }} -gt ${{ env.MAX_IMAGE_SIZE }} ]; then
          echo "Image size is greater than the threshold."
          exit 1
        else
          echo "Image size is within the threshold."
        fi